### PR TITLE
Expose to the user which state is the final state.

### PR DESCRIPTION
**Pull request by ltratt**
Since a state table can only have a single accept entry, exposing this to the user is safe. This is needed for some work in lrpar.

### CODE REVIEW

**Comment by ptersilie** [comment]
Code looks okay. The commit message says this is useful in some cases. Could you elaborate that? The accept state is in my experience almost always (if not always) 1, so I am not sure what the user gains from this information.

**Comment by ltratt** [comment]
You're right, the message was vague -- sorry!

It's necessary for a PR in lrpar I'm working on. In essence, when I'm calculating stuff for the dist/A* algorithm, I have to know which state the "outgoing edge" for the graph is contained within. In lrtable, that's not always going to be state 1 because there is some non-determinism in the way things are calculated. For example, the first example I just checked it had in state 2.

**Comment by ptersilie** [comment]
I see. I just quickly tried some grammars in Eco and all of them were 1 which confirmed my assumption bases on that the starting rule is usually in state 1 so that's where the accept state must also be. Do you mean the non-determinism in creating the state graph? I guess it can happen that state 1 and another state are merged into one and the state number with the starting rule changes although I have never seen that happen.

**Comment by ltratt** [comment]
Indeed, in the example I looked at, it's because of merging. Whether that's critical or not, I don't know.

Either way, I don't think one would want to *rely* on it always be state 1, because some other change in the future might make it sensible to use another state for the final state.

**Comment by ptersilie** [comment]
Of course. If it can happen it's definitely useful to know what the ending state is. I was just surprised that that merging doesn't choose state 1 as the base. But I guess that's due to the nondeterminism of which state causes the merge first. I don't think it's worth changing the merging to prioritise the smaller state number, so I am happy with this PR.

**Comment by ltratt** [comment]
Thinking more about this, I think you're right that this is due to merging (in our case, due to Pager's algorithm).

**Comment by ptersilie** [comment]
It's the only thing that makes sense. At least at the moment. To accept a program we always need to end up in the start rule, which is always in state 1 (I guess you could code it to be in another state, but anyone with a brain would choose state 1 for this). So only through a merge can the starting rule end up in a different state, which I guess happens when the merge is `merge(statex, state1)` instead of `merge(state1, statex)`.

**Pull request merged**
