### PR TITLE
The state_actions iterator should reflect state_action and return a TIdx.

### PR DESCRIPTION
**Pull request by ltratt**
I should have done this in the previous PR. Mea culpa!

### CODE REVIEW

**Comment by snim2** [comment]
Do you want to re-word that commit message before I merge?

**Comment by ltratt** [comment]
In what way?

**Comment by snim2** [comment]
Just that you mention the PRs, which are a GitHub thing rather than a Git thing.

**Comment by ltratt** [comment]
Yes, I had wanted to say "previous commit", but the merge commit messes with that abstraction. I think "PR" is probably the least-worst option, but I can be convinced otherwise.

**Comment by snim2** [comment]
Personally I would have said something like "before the last merge" or "before the merge with <branch>", but if you want me to merge this as-is I don't mind.

**Comment by ltratt** [comment]
Point taken. Fix pushed.

**Pull request merged**
