### PR TITLE
Refactor to cfgrammar

### PR DESCRIPTION
**Pull request by ltratt**
This PR rips out the stuff that's moved to `cfgrammar`, and links to that new library. The changes in both commits are mostly mechanical.

### CODE REVIEW

**Comment by snim2** [comment]
I think that travis fail might just be the result of pushing too soon

**Comment by ltratt** [comment]
Yeah, I've kicked it...

**Comment by snim2** [comment]
This looks OK to me, if @ptersilie and Travis are happy I will squash

**Comment by ltratt** [comment]
No squashing please!

**Comment by snim2** [comment]
I meant merge, sorry

**Comment by ptersilie** [comment]
Go ahead.

**Pull request merged**
