### PR TITLE
Report accept/reduce conflicts via a Result rather than a panic.

### PR DESCRIPTION
**Pull request by ltratt**
I thought that we *might* be able to catch this earlier than table generation by detecting "pointless" cycles / loops. However, I think (but need to confirm) that there are some valid LR grammars which can use this idiom (albeit pointlessly). So I need to think a bit more about that before doing something; this commit, at least, gives the user some chance of debugging their problem.

Addresses #63.

### CODE REVIEW

**Comment by snim2** [comment]
This sounds good, but am I right in thinking that `lrpar` will need a commit to catch it up with these API changes?

**Comment by ltratt** [comment]
Yes, but that'll be a separate (very simple) PR.

**Comment by snim2** [comment]
OK, so in that case I can't test this in rstreediff yet, but I've read through the code and it all looks sensible to me. @ptersilie may have some more useful comments!

**Comment by ptersilie** [comment]
Why isn't the accept/reduce conflicts together with the other conflicts? You even have a comment saying "/// The various different possible Yacc parser errors." but it only lists this one.

**Comment by ltratt** [comment]
Reduce/reduce and shift/reduce are handled in a different way. I don't have test cases for the other types of conflict (I don't even know if they can happen).

**Comment by ptersilie** [comment]
Can't spot any problems. Can merge if Laurie gives his ok.

**Comment by ltratt** [comment]
If you guys are OK with it, please go ahead.

**Comment by ltratt** [comment]
[BTW, I lied; this doesn't require an update in lrpar.]

**Comment by snim2** [comment]
Ah yes, I can build `lrpar` with this branch too, but not `rstreediff`, interestingly.

**Comment by ptersilie** [comment]
Merged!

**Pull request merged**
