### PR TITLE
Modernise the code a touch

### PR DESCRIPTION
**Pull request by ltratt**
This PR brings lrtable up to more modern Rust standards: each commit is self-contained and (hopefully) self-describing.

### CODE REVIEW

**Comment by snim2** [comment]
Generally this looks good to me, but if I search the code for `from` calls there are still quite a few. Some of these are clearly converting vectors, and so not relevant to this PR. However there are a lot like this:
`usize::from(s0)` -- do those really need a `from` call?

**Comment by ltratt** [comment]
The `usize` calls need to be explicit, yes (if nothing else, the type inferencer fails without them).

**Comment by snim2** [comment]
OK. Rather than a `from` call I would have expected something more like:

```rust
struct MyIndex { index: usize }
impl MyIndex {
    pub fn index(&self) { return self.index }
...
}
?

**Comment by ltratt** [comment]
Ah, I think I see what you mean. Let me try something...

**Comment by ltratt** [comment]
Ah, no, I don't think I can do this easily. I think I'd have to make new Vec/HashTable types for the new index types, which feels like too much boilerplate, given that their implementation doesn't leak outside this library. Any thoughts?

**Comment by snim2** [comment]
This is interesting. I have exactly the same issue with rstreediff, and I also didn't want to make `MyIndex.index` (or whatever) public, and so I added another method to the structs that the index points to: https://github.com/softdevteam/rstreediff/blob/master/src/lib/ast.rs#L317-L320

Not sure if that is relevant in your situation?

**Comment by ltratt** [comment]
I don't think it's the same thing, but I'm prepared to be corrected. In fact, I'm not even sure if that method that you've linked to is ever called? Since it's not part of an `impl Index`, I think it's just a "random" (if you see what I mean) method that happens to be called `index`. But I can't see anywhere in rstreediff that calls `index` explicitly?

I might be very wrong about this...

**Comment by snim2** [comment]
It looks like you are right, I'm sure I've used it in the past, but I guess those calls got refactored out, in favour of an attribute: https://github.com/softdevteam/rstreediff/blob/master/src/lib/ast.rs#L246

**Comment by ltratt** [comment]
OK, so I think for the time being let's go with what we have in this PR. I will cogitate for a while, and maybe a nicer mechanism will make itself known.

**Comment by snim2** [comment]
OK, you will probably want to squash...

**Comment by ltratt** [comment]
I think the commits are usefully distinct and stand-alone in this case, so I'd prefer not to.

**Pull request merged**
